import os
import argparse
import json
from datetime import datetime

# Default configuration
DEFAULT_CONFIG = {
    "output_file": "app_context.txt",
    "include_dirs": ["./src", "./app"],
    "exclude_patterns": ["node_modules", "__pycache__", ".git", "venv", ".next", "build", "dist"],
    "include_extensions": [".py", ".js", ".ts", ".tsx", ".java", ".cpp", ".c", ".cs"],
    "summarize_frontend": True,
    "frontend_extensions": [".tsx", ".jsx", ".vue"],
    "min_file_size": 100  # Bytes, to skip empty/small files
}

def load_config(config_file):
    """Load configuration from a JSON file, merging with defaults."""
    config = DEFAULT_CONFIG.copy()
    if os.path.exists(config_file):
        with open(config_file, "r", encoding="utf-8") as f:
            user_config = json.load(f)
            config.update(user_config)
    return config

def should_exclude(path, exclude_patterns):
    """Check if a path matches any exclusion patterns."""
    return any(pattern in path for pattern in exclude_patterns)

def process_directory(directory, config):
    """Collect files to process from a directory based on config."""
    files_to_process = []
    for root, dirs, files in os.walk(directory):
        if should_exclude(root, config["exclude_patterns"]):
            continue
        for file in files:
            full_path = os.path.join(root, file)
            if should_exclude(full_path, config["exclude_patterns"]):
                continue
            file_ext = os.path.splitext(file)[1].lower()
            if file_ext in config["include_extensions"]:
                if os.path.getsize(full_path) > config["min_file_size"]:
                    files_to_process.append(full_path)
    return files_to_process

def summarize_frontend(file_path, content, config):
    """Summarize frontend files to reduce token count, keeping logic."""
    if config["summarize_frontend"] and any(ext in file_path for ext in config["frontend_extensions"]):
        lines = content.splitlines()
        summary = []
        keywords = ["useState", "useEffect", "axios", "fetch", "navigate", "async", "await"]
        for line in lines:
            if any(kw in line for kw in keywords):
                summary.append(line.strip())
        return "\n".join(summary) if summary else "UI Component (summarized)"
    return content

def generate_context(args, config):
    """Generate the context file based on provided arguments and config."""
    all_files = []
    for directory in config["include_dirs"]:
        if os.path.exists(directory):
            all_files.extend(process_directory(directory, config))
    
    all_files.sort(key=lambda x: x.lower())  # Consistent ordering
    
    with open(args.output, "w", encoding="utf-8") as f:
        # Write header
        f.write(f"# App Context | {datetime.now().strftime('%b %d, %Y')}\n")
        f.write(f"Purpose: {args.purpose or 'Generic application context'}\n")
        f.write(f"Tech: {args.tech or 'Various'}\n")
        f.write("Generated by code2context.py\n\n")
        
        # Write file contents
        for file_path in all_files:
            rel_path = file_path[2:] if file_path.startswith("./") else file_path
            with open(file_path, "r", encoding="utf-8") as code_file:
                content = code_file.read()
                content = summarize_frontend(file_path, content, config)
                f.write(f"=== {rel_path} ===\n{content}\n\n")
    
    print(f"Created {args.output}, size: {os.path.getsize(args.output) / 1024:.2f} KB")

def main():
    parser = argparse.ArgumentParser(description="Generate a compact context file for any app, optimized for LLMs.")
    parser.add_argument("--output", default=DEFAULT_CONFIG["output_file"], help="Output file path")
    parser.add_argument("--config", default="context_config.json", help="Path to config JSON file")
    parser.add_argument("--purpose", help="Brief description of the app's purpose")
    parser.add_argument("--tech", help="Tech stack description")
    parser.add_argument("--dirs", nargs="+", help="Directories to scan (overrides config)")
    parser.add_argument("--exts", nargs="+", help="File extensions to include (overrides config)")
    
    args = parser.parse_args()
    
    # Load and update config
    config = load_config(args.config)
    if args.dirs:
        config["include_dirs"] = args.dirs
    if args.exts:
        config["include_extensions"] = args.exts
    
    generate_context(args, config)

if __name__ == "__main__":
    main()